#!/bin/sh
# example postshot script
# to activate, copy to /mnt/local/postshot
mdsConnect andros
mdsOpen acq1001
mdsPutCh --site=1 --field=A017_1.CH%02d -D=/dev/shm/transient/ch/%02d -v 1 --expr %calsig 1:4
mdsValue setEvent\(\'acq1001done\',42ub\)
mdsClose

