#!/bin/sh
set -e
MDSHOST=andros
HN=$(hostname)
mdsConnect $MDSHOST
mdsOpen ${HN}
mdsPutCh -b 1 --site=0  --field=AI.CH%02d --expr %calsig :
# use next line if NCHAN > 99
#mdsPutCh --site=0  --field=AI.CH%03d --expr %calsig :
mdsValue setEvent\(\'${HN}_done\',42ub\)
mdsClose
mdsDisconnect

